const orderData = [
  {
    id: 1,
    customer: "John Doe",
    product: "product1",
    category: "jeans",
    size: "M",
    color: "Blue",
    price: "$40.00",
    quantity: 2,
    totalPrice: "$80.00",
    status: "Processing",
    date: "2024-06-15",
    actions: ["Edit", "Delete"],
  },
  {
    id: 2,
    customer: "Jane Smith",
    product: "product2",
    category: "shirt",
    size: "L",
    color: "Red",
    price: "$25.00",
    quantity: 1,
    totalPrice: "$25.00",
    status: "In Delivery",
    date: "2024-06-14",
    actions: ["Edit", "Delete"],
  },
  {
    id: 3,
    customer: "Alice Johnson",
    product: "Black Shoes",
    category: "shoes",
    size: "S",
    color: "Black",
    price: "$60.00",
    quantity: 1,
    totalPrice: "$60.00",
    status: "Cancelled",
    date: "2024-06-13",
    actions: ["Edit", "Delete"],
  },
  {
    id: 4,
    customer: "Bob Brown",
    product: "product4",
    category: "jeans",
    size: "M",
    color: "White",
    price: "$15.00",
    quantity: 3,
    totalPrice: "$45.00",
    status: "Processing",
    date: "2024-06-12",
    actions: ["Edit", "Delete"],
  },
  {
    id: 5,
    customer: "Charlie Davis",
    product: "Green Jacket",
    category: "shirt",
    size: "XL",
    color: "Green",
    price: "$80.00",
    quantity: 1,
    totalPrice: "$80.00",
    status: "In Delivery",
    date: "2024-06-11",
    actions: ["Edit", "Delete"],
  },
  {
    id: 6,
    customer: "John Doe",
    product: "Blue Jeans",
    category: "jeans",
    size: "M",
    color: "Blue",
    price: "$40.00",
    quantity: 2,
    totalPrice: "$80.00",
    status: "Processing",
    date: "2024-06-15",
    actions: ["Edit", "Delete"],
  },
  {
    id: 7,
    customer: "Jane Smith",
    product: "Red Shirt",
    category: "shirt",
    size: "L",
    color: "Red",
    price: "$25.00",
    quantity: 1,
    totalPrice: "$25.00",
    status: "In Delivery",
    date: "2024-06-14",
    actions: ["Edit", "Delete"],
  },
  {
    id: 8,
    customer: "Alice Johnson",
    product: "Black Shoes",
    category: "shoes",
    size: "L",
    color: "Black",
    price: "$60.00",
    quantity: 1,
    totalPrice: "$60.00",
    status: "Cancelled",
    date: "2024-06-13",
    actions: ["Edit", "Delete"],
  },
  {
    id: 9,
    customer: "Bob Brown",
    product: "product9",
    category: "jeans",
    size: "L",
    color: "White",
    price: "$15.00",
    quantity: 3,
    totalPrice: "$45.00",
    status: "Processing",
    date: "2024-06-12",
    actions: ["Edit", "Delete"],
  },
  {
    id: 10,
    customer: "Charlie Davis",
    product: "Green Jacket",
    category: "shirt",
    size: "XL",
    color: "Green",
    price: "$80.00",
    quantity: 1,
    totalPrice: "$80.00",
    status: "In Delivery",
    date: "2024-06-11",
    actions: ["Edit", "Delete"],
  },
  {
    id: 11,
    customer: "John Doe",
    product: "Blue Jeans",
    category: "jeans",
    size: "M",
    color: "Blue",
    price: "$40.00",
    quantity: 2,
    totalPrice: "$80.00",
    status: "Processing",
    date: "2024-06-15",
    actions: ["Edit", "Delete"],
  },
  {
    id: 12,
    customer: "Jane Smith",
    product: "Red Shirt",
    category: "shirt",
    size: "L",
    color: "Red",
    price: "$25.00",
    quantity: 1,
    totalPrice: "$25.00",
    status: "In Delivery",
    date: "2024-06-14",
    actions: ["Edit", "Delete"],
  },
  {
    id: 13,
    customer: "Alice Johnson",
    product: "Black Shoes",
    category: "shoes",
    size: "M",
    color: "Black",
    price: "$60.00",
    quantity: 1,
    totalPrice: "$60.00",
    status: "Cancelled",
    date: "2024-06-13",
    actions: ["Edit", "Delete"],
  },
  {
    id: 14,
    customer: "Bob Brown",
    product: "product14",
    category: "shoes",
    size: "S",
    color: "White",
    price: "$15.00",
    quantity: 3,
    totalPrice: "$45.00",
    status: "Processing",
    date: "2024-06-12",
    actions: ["Edit", "Delete"],
  },
  {
    id: 15,
    customer: "Charlie Davis",
    product: "product15",
    category: "shirt",
    size: "XL",
    color: "Green",
    price: "$80.00",
    quantity: 1,
    totalPrice: "$80.00",
    status: "In Delivery",
    date: "2024-06-11",
    actions: ["Edit", "Delete"],
  },
];

const tableHeaders = [
  "ID",
  "Customer",
  "Product",
  "Category",
  "Size",
  "Color",
  "Price",
  "Quantity",
  "Total Price",
  "Status",
  "Date",
  "Actions",
];

export { orderData, tableHeaders };
