import product1 from "@/assets/img/product1.jpg";

const productData = [
  {
    id: 1,
    img: product1,
    name: "Sample Product",
    category: "Jeans",
    priceOriginal: "$10.00",
    priceSale: "$8.00",
    colors: [, "red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 120,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 2,
    img: product1,
    name: "Another Product",
    category: "Shirt",
    priceOriginal: "$20.00",
    priceSale: "$15.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 10,
    status: "Out of Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 3,
    img: product1,
    name: "Third Product",
    category: "Shoes",
    priceOriginal: "$30.00",
    priceSale: "$25.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 0,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 4,
    img: product1,
    name: "Fourth Product",
    category: "Jeans",
    priceOriginal: "$40.00",
    priceSale: "$35.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 105,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 5,
    img: product1,
    name: "Fifth Product",
    category: "Shirt",
    priceOriginal: "$40.00",
    priceSale: "$35.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 10,
    status: "Out of Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 6,
    img: product1,
    name: "Sixth Product",
    category: "Jeans",
    priceOriginal: "$40.00",
    priceSale: "$35.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 100,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 7,
    img: product1,
    name: "Seventh Product",
    category: "Jeans",
    priceOriginal: "$40.00",
    priceSale: "$35.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 100,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },

  {
    id: 8,
    img: product1,
    name: "Sample Product",
    category: "Jeans",
    priceOriginal: "$10.00",
    priceSale: "$8.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 120,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 9,
    img: product1,
    name: "Another Product",
    category: "Shirt",
    priceOriginal: "$20.00",
    priceSale: "$15.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 10,
    status: "Out of Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 10,
    img: product1,
    name: "Third Product",
    category: "Shoes",
    priceOriginal: "$30.00",
    priceSale: "$25.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 0,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 11,
    img: product1,
    name: "Fourth Product",
    category: "Jeans",
    priceOriginal: "$40.00",
    priceSale: "$35.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 105,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 12,
    img: product1,
    name: "Fifth Product",
    category: "Shirt",
    priceOriginal: "$40.00",
    priceSale: "$35.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 10,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 13,
    img: product1,
    name: "Sixth Product",
    category: "Jeans",
    priceOriginal: "$40.00",
    priceSale: "$35.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 100,
    status: "Out of Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 14,
    img: product1,
    name: "Seventh Product",
    category: "Jeans",
    priceOriginal: "$40.00",
    priceSale: "$35.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 100,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },

  {
    id: 15,
    img: product1,
    name: "Sample Product",
    category: "Jeans",
    priceOriginal: "$10.00",
    priceSale: "$8.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 120,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 16,
    img: product1,
    name: "Another Product",
    category: "Shirt",
    priceOriginal: "$20.00",
    priceSale: "$15.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 10,
    status: "Out of Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 17,
    img: product1,
    name: "Third Product",
    category: "Shoes",
    priceOriginal: "$30.00",
    priceSale: "$25.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 0,
    status: "Low Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 18,
    img: product1,
    name: "Fourth Product",
    category: "Jeans",
    priceOriginal: "$40.00",
    priceSale: "$35.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 105,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 19,
    img: product1,
    name: "Fifth Product",
    category: "Shirt",
    priceOriginal: "$40.00",
    priceSale: "$35.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 10,
    status: "Out of Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 20,
    img: product1,
    name: "Sixth Product",
    category: "Jeans",
    priceOriginal: "$40.00",
    priceSale: "$35.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 100,
    status: "Low Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 21,
    img: product1,
    name: "Seventh Product",
    category: "Jeans",
    priceOriginal: "$40.00",
    priceSale: "$35.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 100,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },

  {
    id: 22,
    img: product1,
    name: "Sample Product",
    category: "Jeans",
    priceOriginal: "$10.00",
    priceSale: "$8.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 120,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 23,
    img: product1,
    name: "Another Product",
    category: "Shirt",
    priceOriginal: "$20.00",
    priceSale: "$15.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 10,
    status: "Out of Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 24,
    img: product1,
    name: "Third Product",
    category: "Shoes",
    priceOriginal: "$30.00",
    priceSale: "$25.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 0,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 25,
    img: product1,
    name: "Fourth Product",
    category: "Jeans",
    priceOriginal: "$40.00",
    priceSale: "$35.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 105,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 26,
    img: product1,
    name: "Fifth Product",
    category: "Shirt",
    priceOriginal: "$40.00",
    priceSale: "$35.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 10,
    status: "Out of Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 27,
    img: product1,
    name: "Sixth Product",
    category: "Jeans",
    priceOriginal: "$40.00",
    priceSale: "$35.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 100,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 28,
    img: product1,
    name: "Seventh Product",
    category: "Jeans",
    priceOriginal: "$40.00",
    priceSale: "$35.00",
    colors: ["red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 100,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },
];

const tableHeaders = [
  "ID",
  "Name",
  "Category",
  "Color",
  "Size",
  "Price",
  "Inventory",
  "Status",
  "Actions",
];
export { productData, tableHeaders };
