const productData = [
  {
    id: 1,
    img: "",
    name: "Sample Product",
    category: "Jeans",
    priceOriginal: "$10.00",
    priceSale: "$8.00",
    colors: ["all", "red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 100,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 2,
    img: "",
    name: "Another Product",
    category: "Shirt",
    priceOriginal: "$20.00",
    priceSale: "$15.00",
    colors: ["all", "red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 100,
    status: "Out of Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 3,
    img: "",
    name: "Third Product",
    category: "Shoes",
    priceOriginal: "$30.00",
    priceSale: "$25.00",
    colors: ["all", "red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 100,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 4,
    img: "",
    name: "Fourth Product",
    category: "Jeans",
    priceOriginal: "$40.00",
    priceSale: "$35.00",
    colors: ["all", "red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 100,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 5,
    img: "",
    name: "Fifth Product",
    category: "Shirt",
    priceOriginal: "$40.00",
    priceSale: "$35.00",
    colors: ["all", "red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 10,
    status: "Out of Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 6,
    img: "",
    name: "Sixth Product",
    category: "Jeans",
    priceOriginal: "$40.00",
    priceSale: "$35.00",
    colors: ["all", "red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 100,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },
  {
    id: 7,
    img: "",
    name: "Seventh Product",
    category: "Jeans",
    priceOriginal: "$40.00",
    priceSale: "$35.00",
    colors: ["all", "red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    inventory: 100,
    status: "In Stock",
    actions: ["Edit", "Delete"],
  },
];

const tableHeaders = [
  "ID",
  "Name",
  "Category",
  "Color",
  "Size",
  "Price",
  "Inventory",
  "Status",
  "Actions",
];
export { productData, tableHeaders };
