// constants.js

export const tableHeaders = [
  "ID",
  "Name",
  "Email",
  "Role",
  "Status",
  "Actions",
];

export const mockUserData = {
  status: 200,
  message: "user list",
  data: {
    data: [
      {
        id: 1,
        userName: "admin",
        fullName: "Admin",
        gender: "MALE",
        dateOfBirth: null,
        email: "lhhuy2005@gmail.com",
        phone: null,
        avatar:
          "https://cdn.hstatic.net/products/1000253775/160_jogger_070-16_3089aa1bc8d64f2c851f3629289cefaf_1024x1024.jpg",
        status: "ACTIVE",
        point: null,
        verifiedEmail: true,
        addressResponses: [],
        totalSpent: 0.0,
        userRankResponse: null,
        roles: [
          {
            id: 1,
            name: "ADMIN",
            description: "Administrator",
            permissions: [],
          },
        ],
      },
      {
        id: 2,
        userName: "alex",
        fullName: "alex",
        gender: "MALE",
        dateOfBirth: "2005-07-06",
        email: "lehuuhuy211405@gmail.com",
        phone: "0399097211",
        avatar: null,
        status: "ACTIVE",
        point: 52,
        verifiedEmail: true,
        addressResponses: [],
        totalSpent: 1479001.0,
        userRankResponse: {
          id: 2,
          name: "SILVER",
          minSpent: 1000000.0,
          status: "ACTIVE",
        },
        roles: [
          {
            id: 2,
            name: "USER",
            description: "User",
            permissions: [],
          },
        ],
      },
      {
        id: 3,
        userName: "huy",
        fullName: "huy",
        gender: "MALE",
        dateOfBirth: "2005-11-02",
        email: "lehuuhuy211405@gmail.com",
        phone: "0399097211",
        avatar: null,
        status: "ACTIVE",
        point: 0,
        verifiedEmail: false,
        addressResponses: [
          {
            id: 1,
            province: "Hồ Chí Minh",
            district: "Quận Bình Tân",
            ward: "Phường Bình Hưng Hoà A",
            provinceId: 202,
            districtId: 1458,
            wardId: "27439",
            streetAddress: "94A Lô Tư, phường Bình Hưng Hoà A, Quận Bình Tân",
            addressType: "HOME",
            customerName: "Lê Hữu Huy",
            phoneNumber: "0399097211",
            status: "ACTIVE",
            defaultAddress: true,
          },
        ],
        totalSpent: 0.0,
        userRankResponse: {
          id: 1,
          name: "BRONZE",
          minSpent: 0.0,
          status: "ACTIVE",
        },
        roles: [
          {
            id: 4,
            name: "ORDER_STAFF",
            description: "Order staff",
            permissions: [],
          },
          {
            id: 3,
            name: "WAREHOUSE_STAFF",
            description: "Warehouse staff",
            permissions: [],
          },
        ],
      },
    ],
    pageNumber: 0,
    totalPages: 1,
    totalElements: 3,
    pageSize: 5,
  },
};
